### ISSUE TITLE
Layout issues on small screens

### ISSUE THREAD

**Issue by easyaspi314** [Evisceration/android_packages_apps_DeviceControl#12]
Version 0.8.4 beta
Android 4.1.2
3.8" 320x480 screen, 160dpi

Using this app is very inefficient on small screens, and there are currently some huge layout issues.

1. Lists (like Device Info) have far too much vertical padding. I didn't check, but I think standard ListView height would be better for it.

2. Unrelated, but don't use system icons unless using the Gingerbread theme.The search icon is gray, the other icons are white.

3. In the App List, disabled apps are gray, but with the padding/shadow grayed too.

4. Text is cut off. On small screens, it's one thing scrolling through a 72dp list item with multiple lines and another thing scrolling through blank padding.

5. In the settings, the Shell Context option looks like this:

***Shell***

***Sh..***
*The 
cont
ext
unde* &nbsp; &nbsp; Normal     *(full-width spinner)*
*r* &nbsp; &nbsp; &nbsp; &nbsp; _________________________________<
*whic
h
Devi
ce
Cont*

I can provide screenshots if needed later.

**Comment by Evisceration** [comment]
1, 3, 4 and 5 are a problem caused the library i am switching to and which is in active development and far from being finished.
https://github.com/Evisceration/MaterialPreferences

Thanks for the report, unfortunately i do not have such a small device. Will need to get an emulator for such cases.
I am keeping things in the beta phase until the complete relayouting is done.

I have a search icon added for mdpi up to xxxhdpi. i do not plan to support ldpi devices.
Can you tell me in which locations the old icons are appearing, so i can fix it up and work around the appcompat library?

**Comment by Evisceration** [comment]
refactored the settings entry now, added the spinner to the bottom instead of adding it right. screenshot below

![screenshot_2015-07-05-17-56-34](https://cloud.githubusercontent.com/assets/2779871/8512366/7b34f32c-233f-11e5-8fc9-1cf4d221eb59.png)

also working on the material preferences library which should fix the other issues then as well, so closing this issue for now.
