### ISSUE TITLE
stuck on checking for root

### ISSUE THREAD

**Issue by mdutcher** [Evisceration/android_packages_apps_DeviceControl#8]
Well, the titel says a lot, I have waited for 10 minutes and it is still saying checking for root.
My device is a huawei G700-U10

**Comment by Evisceration** [comment]
could you attach a log please?

**Comment by mdutcher** [comment]
not a pro at this XD
Where can I find the log?

**Comment by mdutcher** [comment]
fixed it, superSU was doing weird things,,

**Comment by Evisceration** [comment]
a log you have to take with developer settings enabled and ADB.
but there is no need to do so if it got fixed for you :)

leaving this open for some time and if you get any issues, please let me know and i will have a look at it!
